spring.application.name=security
spring.security.user.name=imran
spring.security.user.password=123

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test 
spring.datasource.username=sa
spring.datasource.password=

spring.app.secret=vf684gvf15f435f4v68f4v4fdv4vfvf35v4f35v4f34b
spring.app.jwtExpirationMs=36000000